name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: lts/*
          check-latest: true
      - run: npm ci
      - run: npx nx typecheck kilo-ai-cli
      - run: npx nx lint kilo-ai-cli
      - run: npx nx test kilo-ai-cli
      - run: npx nx build kilo-ai-cli
